### ISSUE TITLE
Problem loading .dat map file on BeepSaber demo

### ISSUE THREAD

**Issue by zweihander11** [GodotVR/godot-oculus-mobile-asset#5]
Hello
I recently just got a Quest2 and managed to install and run this kit perfectly. I love it!
The BeepSaber demo runs fine on PC but when sideloaded to the Quest I get the Error saying the Json file can't be loaded from the .dat

Any ideas why this might be? Any hint would be appreciated.

I already checked whether the file exists on the device and messed with files directory to ensure proper access but still no clue.
I'm thinking it has something to do with the manifest but I'm not sure, plus I'm not expert in Android Manifest.

Thank you for sharing and any help you can provide

**Comment by NeoSpark314** [comment]
Hi,

thanks for reporting. I will try and see if I can reproduce this issue; I don't have a Quest2 but maybe it is related to the current godot version in combination with the demo (what godot version are you using?). Did you get the toolkit from the asset library or from github directly?

Could you maybe reopen the issue at https://github.com/NeoSpark314/godot_oculus_quest_toolkit; this repo here where you opened the issue is only for the godot quest module and does not contain the oculus quest toolkit (which is in the repo linked above). How did you get here? Maybe there is some wrong link somewhere that needs to be updated.

**Comment by zweihander11** [comment]
Thanks for replying! To be honest I'm not sure how I got here. I was reading the documentation here when I posted the issue. 
https://github.com/NeoSpark314/godot_oculus_quest_toolkit/wiki
I will reopen the issue there with updated details.
I'm using Godot 3.2.1
